-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: pootle/static/js/vendor|pootle/static/css/sprite.css
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: pootle/static/js/vendor|pootle/templates/contact_form/report_form_body.txt|pootle/static/css/sprite.css
    -   id: fix-encoding-pragma
    -   id: flake8
        args: ['--config=setup.cfg', '--ignore=E129,E226,E402,W503,I,N,E731']
        exclude: __pycache__|migrations|conf.py|_build|.tox|pootle/static|pootle/translations|pootle/locale|pootle/assets|templates
- repo: /Users/dwayne/dev/pre-commit-hooks
  sha: 'feature/sphinx-hook'
  hooks:
    - id: sphinx-docs
      args: ['-bhtml', '-d docs/_build/doctrees', '-W', '-q', '-j 4', 'docs', 'docs/_build/html']
      exclude: README.rst|CONTRIBUTING.rst
